### ISSUE TITLE
Prim's

### ISSUE THREAD

**Issue by NovaSagittarii** [NovaSagittarii/graph-algorithm-visualization#6]
Find your file in `src/algorithm/*.js`
See `src/algorithm/BFS.js` for an example or poke me.

**Comment by AnPhu-D** [comment]
Please code review

**Comment by GLKumfert** [comment]
Brother linked the wrong issue !!!

**Comment by AnPhu-D** [comment]
Unsure of how to visualize while running but the calculation is there.
