### ISSUE TITLE
Reachability Queries

### ISSUE THREAD

**Issue by NovaSagittarii** [NovaSagittarii/graph-algorithm-visualization#7]
Find your file in `src/algorithm/*.js`
See `src/algorithm/BFS.js` for an example or poke me.

**Comment by GLKumfert** [comment]
https://en.wikipedia.org/wiki/Reachability
Doing thorups

**Comment by NovaSagittarii** [comment]
oops this is a parallel algorithm thing
https://en.wikipedia.org/wiki/Strongly_connected_component#Reachability-based_algorithms
